name: ci-master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    

jobs:
  pipeline:
    name: Pipeline
    uses: MudBlazor/MudBlazor/.github/workflows/template-pipeline.yml@master
    with:
      dotnet-version: 5.0.x
      publish-coverage: true
