name: master-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    

jobs:
  pipeline:
    name: Pipeline
    uses: MudBlazor/MudBlazor/.github/workflows/template-pipeline.yml@master
    with:
      dotnet-version: 5.0.x
      publish-coverage: true
      deploy-web-app: true
      deploy-condition: 'refs/heads/master'
      deploy-web-app-name: mudblazor-staging
    secrets:
      publish-profile: ${{ secrets.PUBLISH_MUDBLAZOR_STAGING }}
